# Generated by Django 5.1.7 on 2025-03-23 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("CYCLING", "Cycling"),
                            ("SWIMMING", "Swimming"),
                        ],
                        max_length=50,
                    ),
                ),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                (
                    "distance",
                    models.FloatField(
                        blank=True, help_text="Distance in kilometers", null=True
                    ),
                ),
                (
                    "calories",
                    models.IntegerField(
                        blank=True, help_text="Calories burned", null=True
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
